### ISSUE TITLE
Global exceptions handling

### ISSUE THREAD

**Issue by oleneveu** [mayuki/Cocona#123]
I would like to add a global exception handler for all commands.

The default behavior is that all exceptions are catched by the handler in `HandleExceptionAndExitMiddleware`.

I have tried to add another middleware to intercept the exception:
```C#
var builder = CoconaApp.CreateBuilder(args);
var app = builder.Build();
var commandDispatcher = app.Services.GetRequiredService<ICoconaCommandDispatcherPipelineBuilder>();
commandDispatcher.UseMiddleware<MyExceptionHandlerMiddleware>();
```

That does not work, and my understanding is that the `HandleExceptionAndExitMiddleware` is added later and takes precedence over my own middleware.

Is there any other way to intercept the exceptions ?

**Comment by mayuki** [comment]
You can apply filters with `app.UseFilter` to handle exceptions in the same way as middleware.

**Comment by oleneveu** [comment]
Thanks, that's what I was looking for.
Sorry for not having found that by myself...
