### ISSUE TITLE
Supporting `HostApplicationBuilder` as one of the `GenericHost` options

### ISSUE THREAD

**Issue by EugeneKrapivin** [mayuki/Cocona#138]
Hey!
I've submitted #137 pull-request attempting to add support for the [`HostApplicationBuilder`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostapplicationbuilder?view=dotnet-plat-ext-8.0).

The reasoning was to move away from a callback style of host bootstrapping to a more linear method. Discussion could be [found here](https://github.com/dotnet/runtime/discussions/81090#discussioncomment-4784551) with an explanation by David Fowler.

Cheers,
Eugene K.

**Comment by EugeneKrapivin** [comment]
#137 merged

**Comment by mkalinski93** [comment]
Is it just me or does the extension does not exist?
I have installed Cocona v2.2.0 in my project but Host.CreateApplicationBuilder does not seems to have an extension method for cocona?

<!-- Uploading "image.png"... —>
