### ISSUE TITLE
Feature request: shell completions (suggestions)

### ISSUE THREAD

**Issue by dahlia** [mayuki/Cocona#14]
Nowadays it's quite common that CLI programs support *shell completions*, so that users quickly get the usage of options/subcommands/arguments without reading `--help` or `man`.  Fortunately Corona manages to know the entire interface of a command-line program built on it, completions could be automatically generated.

FYI some other CLI frameworks have similar features:

- [System.CommandLine](https://github.com/dotnet/command-line-api/wiki/Features-overview#Suggestions)
- [Click](https://click.palletsprojects.com/en/7.x/bashcomplete/) (Python)
- [optparse-applicative](https://github.com/pcapriotti/optparse-applicative#bash-zsh-and-fish-completions) (Haskell)

**Comment by mayuki** [comment]
I agree with your feature request. But, which shell do you think should be supported?
I usually use zsh and bash, so I want to support at least those shells.

- PowerShell
- bash
- zsh
- ...

**Comment by dahlia** [comment]
Yeah, those 3 shells you mentioned seem enough to cover the most of users!

**Comment by mayuki** [comment]
I finally released v1.4.0 with bash and zsh shell completion support.
