### ISSUE TITLE
Passing CoconaAppContext / CancellationToken to a command added with AddCommands<T>

### ISSUE THREAD

**Issue by woha** [mayuki/Cocona#153]
Is there a way to pass the `CoconaAppContext` or a `CancellationToken` to a command, which is added with `app.AddCommands<MyCommand>();`?

I've read in the docs [https://github.com/mayuki/Cocona#shutdown-event-handling](url) that this is possible for `AddCommand`, but couldn't figure out how to do it for `AddCommands<T>`

Or what is the best way to handle e.g. Ctrl+C in a command?

**Comment by JordyThien** [comment]
I was running into the same problem. The answer is somewhat provided in the manual: "Alternatively, you can use ICoconaAppContextAccessor and CoconaAppContext to access CancellationToken.".

Say you have a command `Hello`, you can access the `CancellationToken` as follows:

```
   [Command("Hello")]
   public async Task HelloCmd([FromService] ICoconaAppContextAccessor contextAccessor)
   {
      var ctx = contextAccessor.Current ?? throw new InvalidOperationException();
      while (!ctx.CancellationToken.IsCancellationRequested)
      {
         Console.WriteLine("Hello world!");
         await Task.Delay(100);
      }
   }
```

I've just applied it to my code and it works as you'd expect.

**Comment by woha** [comment]
Thank you very much, Jordy.
This is exactly what I was looking for.
