### ISSUE TITLE
Question: best practice for duplicated options

### ISSUE THREAD

**Issue by moreal** [mayuki/Cocona#29]
For example, now, I'm implementing `Key` command with `Cocona`. In detail, the command will have subcommands which handle key store, like `list`, `import`, at the key store placed. And the key store's path should be set manually. As code...

```csharp
class KeyCommand
{
  public void List([Option]string? keyStorePath = null) { ... }
  public void Import([Option]string? keyStorePath = null) { ... }
}
```

But the `keyStorePath` option is duplicated though the option will be used over all subcommands in `KeyStore` class. So I imagine some codes to remove the code duplication...

```csharp
class KeyCommand
{
  private readonly string _keyStorePath;
  
  public KeyCommand([Option]string? keyStorePath = null) { _keyStorePath = keyStorePath ?? /**/; }
  public void List() { ... }
  public void Import() { ... }
}
```

Can you let me know the solution if it can be achieved with *Cocona* or considering it together through this issue?

**Comment by mayuki** [comment]
Sorry for replying so late.

Unfortunately, there is currently no way to make it work. However, I understand that there is such a use case.
I'm thinking of treating it as an object, like a parameter in ASP.NET Core MVC.

For example, how about the following code?

```csharp
class MyAppCommonParameterSet : ICommandParameterSet
{
    [Option] public string? KeyStorePath { get; set; }
}

class KeyCommand
{
    public void List(MyAppCommonParameterSet commonParameterSet) { ... }
    public void Import(MyAppCommonParameterSet commonParameterSet) { ... }
} 
```

**Comment by moreal** [comment]
I'm sorry for replying so late, too 😅 

As I understood, it seems great way because the duplicated parameters are resolved by inheritance. If the feature applied, how does the existed way become? Replaced or coexist?

**Comment by mayuki** [comment]
Existing parameters are assumed to be used as is. Class definitions will be expanded into parameters.

```csharp
class MyAppCommonParameterSet : ICommandParameterSet
{
    [Option] public string? KeyStorePath { get; set; }
}

class KeyCommand
{
    // public void List([Option] bool foo, MyAppCommonParameterSet commonParameterSet) { ... }
    public void List([Option] bool foo, [Option] public string? KeyStorePath) { ... }
} 
```

In the case of class definitions, I'm considering whether and how to specify what is optional.

**Comment by moreal** [comment]
As my understood, you are considering how to specify what method to call when there are conflicted CLI signature, right? I'm not sure that I understood the situation well. Please let me know it if I didn't understand well.

- `public void List([Option] bool foo, MyAppCommonParameterSet ...) { ... }` == `--foo --keyStorePath`
- `public void List([Option] bool foo, string keyStorePath...) { ... }` == `--foo --keyStorePath` conflicts!

In my thought, the best way to resolve it is to provide prebuild MSBuild task to check it.

**Comment by mayuki** [comment]
Sorry for the delay, but I have started to implement this feature/enhancement. 🙂
I am considering throwing a runtime error if the signature conflicts.
