### ISSUE TITLE
string array argument with hyphens

### ISSUE THREAD

**Issue by kareem613** [mayuki/Cocona#38]
I have a string[] argument. When one of the values passed in at the command like contains a hyphen, it's interpreted by Cocona as an argument for it instead of a string value to the Command.

I thought having the string[] parameter being the last one would do the job but it appears any hyphen after a sub-command is interpreted as a switch to Cocona. 

ex.
```cli subcommand -string_to_command```

I want this to execute the `subcommand` with a string value of "-string_to_command"

Is this doable?

**Comment by mayuki** [comment]
Cocona will stop further parsing with `--` just like any other *nix command (ex. `dotnet run -- -myvalue1`).
https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

```
cli subcommand -- -string_to_command
```

**Comment by kareem613** [comment]
Ok. I'll try that out to see if it's another option. 

I tried the IgnoreUnknownOptions attribute. It works the way I'd like it to. Haven't tested enough yet to see what the tradeoffs might be. 

Thanks!

**Comment by kareem613** [comment]
`--` is the way. Thanks for the pointer!
