### ISSUE TITLE
Cocona purpose?

### ISSUE THREAD

**Issue by cfranchuk** [mayuki/Cocona#4]
Out of curiosity, what are the benefits of Cocona? I don't see much that Cocona provides developers that the Generic Host (.net core 2.1-2.2) and the background service (.net core 3+) do not? 

I am not asking to be a jerk, but rather because I work with these two technologies often and was curious if this would benefit my project in a meaningful way.

Thanks,

Craig F.

**Comment by mayuki** [comment]
Thank you for your question.

Cocona is also built on GenericHost. As a result, you can benefit from `Microsoft.Extensions.*`, Such as DI and Logging. [You can also manually integrate `Host` using the Advanced API.](https://github.com/mayuki/Cocona/blob/9d8767912621fe59f3424eca9cedec84c0795ca9/samples/Advanced.GenericHost/Program.cs#L12-L15)

Cocona's purpose is primarily to eliminate tedious boilerplate code such as command-line parsing and help generation.

**Comment by cfranchuk** [comment]
I reviewed the Cocona libraries provided and can see the benefits to console applications. In my use case we are typically running processes as services and don't support passing command-line arguments. Thanks for the information though. The library does make the boilerplate code clean and that initially caught my attention.
