### ISSUE TITLE
Nested subcommands support

### ISSUE THREAD

**Issue by benjiro** [mayuki/Cocona#6]
Wondering if it's possible to support nested subcommands. Having a quick skim over the documentation and code and it doesn't seem currently possible unless I missed something.

For example
`./foo [subcommand] [nested subcommand] [arguments]`

`./foo [subcommand] [nested subcommand] [nested subcommand] [arguments]`

**Comment by mayuki** [comment]
You're right. Currently, Cocona does not support nested subcommands.
I'm considering it, can you please tell me a use case if possible? (Because I know very few commands with nested subcommands. e.g. `netsh`)

**Comment by dantheman999301** [comment]
`kubectl` has a lot of nested subcommands.

**Comment by mayuki** [comment]
I thought`kubectl` has the following form. The second argument looks like an argument, not a subcommand.

```
kubectl get svc,deployment
        ^^^ ^^^^^^^^^^^^^^
         |       |
         |       |--- resource types (1..N)
         |
         |--- subcommand
```

However, when I checked again, I found nested subcommand in several commands, such as `kubectl top`.

```
kubectl top node NODE_NAME
        ^^^ ^^^^
         |    |
         |    |--- nested subcommand
         |
         |--- subcommand
```

**Comment by benjiro** [comment]
@mayuki The use case is basically what you just explained above. I want to convert a bunch of internal tools my company uses under one interface which will require the use of nested sub commands.

**Comment by mayuki** [comment]
Cocona now supports nested sub-command.
https://github.com/mayuki/Cocona#nested-sub-commands

Please feel free to send me feedback!
