### ISSUE TITLE
Hidden commands show up in the suggested list of similar commands

### ISSUE THREAD

**Issue by cwmacdon** [mayuki/Cocona#70]
I think the generated list of similar commands should not include commands tagged as `Hidden`.

https://github.com/mayuki/Cocona/blob/3f3f3ee1c74019ed60a92f4eb23ee38f78b414df/src/Cocona.Core/Command/CoconaBootstrapper.cs#L59

**Comment by cwmacdon** [comment]
awesome thanks :) Any estimate on when the next release might be? we've been working around this and #87

**Comment by mayuki** [comment]
I apologize for the delay, but I have just released v2.2.0.

**Comment by cwmacdon** [comment]
Thank you for your work!
